CREATE DEFINER=`root`@`localhost` EVENT `UpdateAbsences` ON SCHEDULE EVERY 1 DAY STARTS '2024-03-06 23:59:00' ON COMPLETION NOT PRESERVE ENABLE DO UPDATE users
SET ausencias = ausencias + 1
WHERE user_id NOT IN (SELECT DISTINCT(user_id) FROM user_logs WHERE DATE(checkindate) = CURRENT_DATE)
AND DAYOFWEEK(CURRENT_DATE) BETWEEN 2 AND 6